CoreApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using CoreApp.Models;
using CoreApp.Services;
using Microsoft.AspNetCore.Authorization;

namespace CoreApp.Controllers
{
   
    public class DepartmentController : Controller
    {
        private readonly IService<Department, int> _service;

        public DepartmentController(IService<Department, int> service)
        {
            _service = service;
        }
        [Authorize(Policy ="readpolicy")]
        public IActionResult Index()
        {
            var data = _service.GetAsync().Result;
            return View(data);
        }

        [Authorize(Policy = "writepolicy")]
        public IActionResult Create()
        {
            var data = new Department();
            return View(data);
        }

        [HttpPost]
        public IActionResult Create(Department data)
        {
            //try
            //{
                if (ModelState.IsValid)
                {
                    if (data.Capacity <= 0) throw new Exception("Capacity cannot -Ve or Zero");
                    data = _service.CreateAsync(data).Result;
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(data);
                }
            //}
            //catch (Exception ex)
            //{
            //    return View("Error", new ErrorViewModel()
            //    {
            //        ControllerName = RouteData.Values["controller"].ToString(),
            //        ActionName = RouteData.Values["action"].ToString(),
            //        ErrorMessage = ex.Message
            //    }) ;
            //}
        }

        [Authorize(Policy = "writepolicy")]
        public IActionResult Edit(int id)
        {
            var data = _service.GetAsync(id).Result;
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(int id, Department data)
        {
            if (ModelState.IsValid)
            {
                data = _service.UpdateAsync(id, data).Result;
                return RedirectToAction("Index");
            }
            else
            {
                return View(data);
            }
        }

        public IActionResult Delete(int id)
        {
            var data = _service.DeleteAsync(id).Result;
            return RedirectToAction("Index");
        }

    }
}

CoreApp/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using CoreApp.Models;
using CoreApp.Services;
namespace CoreApp.Controllers
{
    public class EmployeeController : Controller
    {

        private readonly IService<Employee, int> _service;
        private readonly IService<Department, int> _dService;

        public EmployeeController(IService<Employee, int> service, IService<Department, int> dService)
        {
            _service = service;
            _dService = dService;
        }
        public IActionResult Index()
        {
            var data = _service.GetAsync().Result;
            return View(data);
        }

        public IActionResult Create()
        {
            var data = new Employee();
            ViewData["DeptRowId"] = _dService.GetAsync().Result;
            return View(data);
        }

        [HttpPost]
        public IActionResult Create(Employee data)
        {
            if (ModelState.IsValid)
            {
                data = _service.CreateAsync(data).Result;
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["DeptRowId"] = _dService.GetAsync().Result;
                return View(data);
            }
        }

        public IActionResult Edit(int id)
        {
            var data = _service.GetAsync(id).Result;
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(int id, Employee data)
        {
            if (ModelState.IsValid)
            {
                data = _service.UpdateAsync(id, data).Result;
                return RedirectToAction("Index");
            }
            else
            {
                return View(data);
            }
        }

        public IActionResult Delete(int id)
        {
            var data = _service.DeleteAsync(id).Result;
            return RedirectToAction("Index");
        }
    }
}

CoreApp/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreApp.Data;
using Microsoft.AspNetCore.Identity;

namespace CoreApp.Controllers
{
    public class RoleController : Controller
    {

        RoleManager<IdentityRole> roleManager;
        

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        public IActionResult Create(IdentityRole role)
        {
            var r = roleManager.CreateAsync(role).Result;
            return RedirectToAction("Index");
        }
    }
}

CoreApp/Views/Shared/CustomError.cshtml
 

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>


<h2>Error Occured as : @ViewData["ErrorMessage"]</h2>
<h2>Action Name : @ViewData["ActionName"]</h2>
<h2>Controller Name: @ViewData["ControllerName"]</h2>

<a asp-action='@ViewData["ActionName"]' asp-controller='@ViewData["ControllerName"]'>Go Back</a> 

CoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Department" asp-action="Index">Department</a></li>
                    <li><a asp-area="" asp-controller="Employee" asp-action="Index">Employee</a></li>
                    <li><a asp-area="" asp-controller="Role" asp-action="Index">Role</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CoreApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>